export const services = [
  {
    slug: 'svarovane-konstrukce',
    title: 'Sva�ovan� konstrukce',
    spec: 'Zak�zkov� v�roba ocelov�ch konstrukc�',
    shortDesc: 'Navrhujeme a vyr�b�me ocelov� sva�ovan� konstrukce pro pr�myslov� haly, technologick� linky a speci�ln� aplikace.',
    description: [
      'Sva�ovan� ocelov� konstrukce jsou z�kladem na�� v�roby. Disponujeme vlastn�m v�robn�m z�zem�m a zku�en�mi sv��e�i, kte�� zvl�daj� jak kusov� zak�zky, tak opakovanou s�riovou v�robu.',
      'Ke ka�d� zak�zce zpracujeme v�robn� dokumentaci a v�stupn� kontroln� z�znamy. Pracujeme dle z�kaznick� dokumentace nebo sami navrhneme konstruk�n� �e�en�.',
      'Kapacitn� jsme schopni realizovat jak jednor�zov� kusov� zak�zky, tak opakovanou s�riovou v�robu. Spolupracujeme s konstruk�n�mi kancel��emi, nebo p�eb�r�me zak�zku p��mo od z�kazn�ka dle jeho v�kresov� dokumentace.',
    ],
    features: ['Nosn� ocelov� konstrukce', 'R�mov� sva�ence a r�my stroj�', 'Technologick� podp�ry a plo�iny', 'Schodi�t�, z�bradl�, l�vky', 'Potrubn� mosty a trasy', 'Speci�ln� p��pravky pro v�robu'],
    image: '/assets/97b4c3e30_generated_25afdfea.png',
  },
  {
    slug: 'tlakove-nadoby',
    title: 'Tlakov� n�doby',
    spec: 'V�roba tlakov�ch celk� pro pr�mysl',
    shortDesc: 'Vyr�b�me tlakov� n�doby stabiln� i transportn�, z�sobn�ky, v�m�n�ky tepla a speci�ln� tlakov� komponenty.',
    description: [
      'V�roba tlakov�ch n�dob je jednou z nejn�ro�n�j��ch oblast� na�� �innosti. Ka�d� n�doba proch�z� d�kladnou kontrolou a revizn� zkou�kou, aby spl�ovala po�adavky z�kazn�ka a podm�nky provozu.',
      'Vyr�b�me stabiln� i transportn� tlakov� n�doby, vzdu�n�ky, z�sobn�ky kapalin, expanzn� n�doby a v�m�n�ky tepla. Materi�l vol�me dle provozn�ho m�dia a podm�nek � od konstruk�n� oceli po nerezy a niklov� slitiny.',
      'Sou��st� dod�vky je v�dy kompletn� technick� dokumentace, v�po�tov� zpr�vy, revizn� den�k a pr�vodn� dokumentace dle po�adavk� z�kazn�ka.',
    ],
    features: ['Tlakov� z�sobn�ky a vzdu�n�ky', 'V�m�n�ky tepla (trubkov�, deskov�)', 'Stabiln� a p�epravn� n�doby', 'Expanzn� n�doby', 'Z�sobn�ky procesn�ch m�di�', 'Revize a rekonstrukce existuj�c�ch n�dob'],
    image: '/assets/9038371a5_generated_3696ff6e.png',
  },
  {
    slug: 'vzduchotechnika',
    title: 'Vzduchotechnika',
    spec: 'Kompletn� VZT syst�my na kl��',
    shortDesc: 'Zaji��ujeme kompletn� dod�vky vzduchotechnick�ch syst�m� � od projektu p�es v�robu potrub� a� po mont� a zprovozn�n�.',
    description: [
      'Vzduchotechnick� syst�my navrhujeme, vyr�b�me a montujeme jako komplexn� dod�vku na kl��. V�roba potrub� prob�h� ve vlastn�ch d�ln�ch na CNC ohra�ovac�ch link�ch, kter� zaru�uj� rozm�rovou p�esnost a rychlost dod�vky.',
      'Realizujeme v�trac�, klimatiza�n� a ods�vac� syst�my pro pr�myslov� provozovny, sklady, potravin��sk� z�vody i ve�ejn� budovy.',
      'Spolupracujeme s projektanty TZB nebo sami zpracujeme projektovou dokumentaci. Zaji��ujeme tak� se��zen�, m��en� pr�tok� a uveden� syst�mu do provozu.',
    ],
    features: ['V�roba VZT potrub� (kruhov� i �ty�hrann�)', 'Pr�myslov� ods�v�n� a filtrace', 'Klimatizace a v�tr�n� v�robn�ch hal', 'Digesto�e a ods�vac� ramena', 'Rekuperace tepla', 'M��en�, se�izov�n� a zprovozn�n�'],
    image: '/assets/0a30f5073_generated_fe3092c9.png',
  },
  {
    slug: 'technologie-cov',
    title: 'Technologie �OV',
    spec: '�ist�rny odpadn�ch vod na kl��',
    shortDesc: 'Dod�v�me kompletn� technologick� celky pro �ist�rny odpadn�ch vod � strojn� vybaven�, potrubn� rozvody a aera�n� syst�my.',
    description: [
      'Technologie �ist�ren odpadn�ch vod jsou jednou z kl��ov�ch oblast� na�� specializace. Dod�v�me kompletn� strojn� vybaven� nov�ch �OV i rekonstrukce a modernizace st�vaj�c�ch provoz�.',
      'Na�e dod�vky zahrnuj� mechanick� p�ed�i�t�n� (�esle, lap�ky p�sku), biologick� stupe� �i�t�n� (aerace, m�ch�n�, dosazovac� n�dr�e), kalov� hospod��stv� i ��dic� syst�my.',
      'Pracujeme pro m�sta, obce i pr�myslov� subjekty. Zaji��ujeme projekci, v�robu, dod�vku, mont� i za�kolen� obsluhy. Nab�z�me tak� servisn� smlouvy na provoz a �dr�bu.',
    ],
    features: ['Strojn� technologie �OV (mechanick� stupe�)', 'Biologick� stupe� � aerace a m�ch�n�', 'Potrubn� rozvody a armaturn� uzly', 'Kalov� hospod��stv� a zahu��ova�e', 'Rekonstrukce a modernizace �OV', 'Za�kolen� obsluhy a servisn� smlouvy'],
    image: '/assets/118271a23_generated_123c53a5.png',
  },
  {
    slug: 'opravy-udrzba',
    title: 'Opravy a �dr�ba',
    spec: 'Servisn� smlouvy a havarijn� z�sahy',
    shortDesc: 'Poskytujeme pravidelnou �dr�bu technologick�ch celk�, opravy stroj� a havarijn� z�sahy v pr�myslov�ch provozech.',
    description: [
      'Servisn� a udr�ovac� �innost prov�d�me pro pr�myslov� podniky, vodohospod��sk� subjekty i komun�ln� sf�ru. Zaji��ujeme jak pl�novanou preventivn� �dr�bu, tak okam�it� havarijn� opravy.',
      'Nab�z�me servisn� smlouvy �it� na m�ru � od �tvrtletn�ch prohl�dek a maz�n� lo�isek po kompletn� ro�n� revize cel�ch technologick�ch celk�. V r�mci smluv garantujeme dobu reakce na havarijn� z�sah.',
      'Disponujeme vlastn� sv��ec� a z�me�nickou kapacitou, tak�e opravy realizujeme okam�it� bez nutnosti subdodavatel�. N�hradn� d�ly zaji��ujeme z ov��en�ch zdroj� nebo vyr�b�me p��mo v na�ich d�ln�ch.',
    ],
    features: ['Preventivn� a prediktivn� �dr�ba', 'Havarijn� opravy (dostupnost 24/7)', 'Rekonstrukce a repase stroj�', 'Opravy ocelov�ch konstrukc� a potrub�', 'V�roba n�hradn�ch d�l�', 'Servisn� smlouvy s garantovanou odezvou'],
    image: '/assets/1ed57d3ea_generated_1a1f1306.png',
  },
  {
    slug: 'elektromontaze',
    title: 'Elektromont�e',
    spec: 'Pr�myslov� elektroinstalace na kl��',
    shortDesc: 'Prov�d�me kompletn� elektromont�n� pr�ce v pr�myslov�ch provozech � od silnoproud�ch rozvod� p�es ��dic� syst�my a� po uv�d�n� do provozu.',
    description: [
      'Elektromont�n� pr�ce realizujeme pro pr�myslov� podniky, v�robn� haly, vodohospod��sk� objekty a komun�ln� stavby. Zaji��ujeme kompletn� dod�vku elektroinstalace na kl�� � od projektu p�es mont� a� po zprovozn�n�.',
      'Prov�d�me silnoproud� rozvody n�zk�ho nap�t�, mont�e rozvad��� a rozvodnic, kabelov� trasy, osv�tlen� pr�myslov�ch hal, uzemn�n� a hromosvody. Specializujeme se na nap�jen� technologick�ch za��zen� a stroj�.',
      'Sou��st� na�ich dod�vek jsou tak� mont�e MaR (m��en� a regulace), zapojen� frekven�n�ch m�ni��, motorov�ch spou�t��� a pr�myslov�ch ��dic�ch syst�m�. Po dokon�en� prac� zaji��ujeme v�choz� revizi elektroza��zen�.',
    ],
    features: [
      'Silnoproud� rozvody NN (do 1 kV)',
      'Mont� rozvad��� a rozvodnic',
      'Kabelov� trasy a �laby',
      'Pr�myslov� osv�tlen� hal a venkovn�ch prostor',
      'Uzemn�n� a hromosvody',
      'Zapojen� stroj� a technologi� (frekven�n� m�ni�e, MaR)',
      'V�choz� a periodick� revize elektroza��zen�',
    ],
    image: '/assets/a07e9b6fe_generated_image.png',
  },
  {
    slug: 'zakazkova-kovovyroba',
    title: 'Zak�zkov� kovov�roba',
    spec: 'Kusov� i malos�riov� v�roba',
    shortDesc: 'Realizujeme individu�ln� zak�zky kovov�roby podle dodan� dokumentace nebo vlastn�ho n�vrhu � od jednoduch�ch d�l� po slo�it� sestavy.',
    description: [
      'Zak�zkov� kovov�roba zahrnuje ve�ker� z�me�nick� a sv��ec� pr�ce pro individu�ln� z�kazn�ky i pr�myslov� podniky. Pracujeme dle z�kaznick� v�kresov� dokumentace nebo sami navrhneme �e�en�.',
      'Disponujeme plazmov�m a kysl�kov�m �ez�n�m, oh�b�n�m, sva�ov�n�m (MIG/MAG, TIG, plamen), vrt�n�m a z�vitov�n�m. Zpracov�v�me konstruk�n� ocel, nerezovou ocel i hlin�k.',
      'Pro fin�ln� �pravu povrchu zaji��ujeme trysk�n�, z�kladn� n�t�ry nebo zprost�edkujeme ��rov� zinek a pr�kov� lakov�n� u ov��en�ch koopera�n�ch partner�.',
    ],
    features: ['�ez�n� � plazma, kysl�kov�, p�esn�', 'Oh�b�n� plechu a profil�', 'Sva�ov�n� MIG/MAG, TIG', 'Nerezov� a hlin�kov� v�robky', 'P��pravky a jedno��elov� za��zen�', 'Povrchov� �pravy a kooperace'],
    image: '/assets/a5e1ce5cb_generated_787e2582.png',
  },
];
